monthConversions={
    "jan":"January",
    "feb":"february",
    "mar":"march",
    "apr":"april",
    "may":"may",
    "jun":"june",
    "jul":"july",
    "aug":"august",
    "sep":"september",
    "oct":"october",
    "nov":"november",
    "dec":"december"
}
print(monthConversions["nov"])
print(monthConversions.get("mar"))